### ISSUE TITLE
Hey 

### ISSUE THREAD

**Issue by ghost** [Palente/SeeDevice#2]
Can you add faction compatibility ?

**Comment by Palente** [comment]
The api is accessible, if you use a public plugin tell to his author to add compatibility with SeeDevice

**Comment by ghost** [comment]
Ok j' espère que il vont le faire ça serais sympa de leur part

**Comment by Palente** [comment]
Oui tu verras bien😀

Le sam. 20 oct. 2018 à 22:18, georgianYT <notifications@github.com> a
écrit :

**Comment by Palente** [comment]
Oui tu verras bien
